import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the contour labeling workspace", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>Palona Contour Lab<\/title>/i);
  assert.match(html, /Palona contour lab/);
  assert.match(html, /Video clip/);
  assert.match(html, /Control JSON/);
  assert.match(html, /Interaction JSON/);
  assert.match(html, /Contours/);
  assert.match(html, /Create interaction/);
  assert.match(html, /Manual objects/);
  assert.match(html, /Create/);
  assert.match(html, /Saved manual objects/);
  assert.match(html, /Defined interactions/);
  assert.match(html, /Export JSON/);
  assert.doesNotMatch(html, /codex-preview|react-loading-skeleton/);
});

test("includes frame sync, contour hit testing, and local file support", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  assert.match(page, /requestVideoFrameCallback/);
  assert.match(page, /metadata\?\.mediaTime \?\? video\.currentTime/);
  assert.match(page, /function frameAtOrBefore/);
  assert.match(page, /function pointInPolygon/);
  assert.match(page, /stepFrame\(-1\)/);
  assert.match(page, /stepFrame\(1\)/);
  assert.match(page, /accept="video\/\*,\.mkv"/);
  assert.match(page, /function parseInteractionFile/);
  assert.match(page, /payload\.interaction_list/);
  assert.match(page, /payload\.manual_objects \?\? \[\]/);
  assert.match(page, /Manual object ID \$\{objectId\} appears more than once/);
  assert.match(page, /manual_objects: manualObjects/);
  assert.match(page, /function loadInteractionsJson/);
  assert.match(page, /function loadManualObjectsJson/);
  assert.match(page, /const interactionText = await file\.text\(\)/);
  assert.match(page, /parseInteractionFile\(JSON\.parse\(interactionText\)\)/);
  assert.match(page, /setInteractions\(loadedInteractions\)/);
  assert.match(page, /setExportedInteractionSignature\(loadedSignature\)/);
  assert.match(page, /setInteractionDraft\(firstInteraction \? cloneInteraction\(firstInteraction\) : null\)/);
  assert.match(page, /Interaction ID \$\{interactionId\} appears more than once/);
  assert.match(page, /new Worker/);
  assert.match(page, /file\.stream\(\)\.getReader\(\)/);
  assert.match(page, /type: "batch"/);
  assert.match(page, /loadedFrames\.push/);
  assert.doesNotMatch(page, /JSON\.parse\(await file\.text\(\)\)/);
  assert.match(page, /track\.contours_xy/);
  assert.match(page, /bbox_xyxy: track\.bbox_xyxy/);
  assert.match(page, /!drewPolygon && track\.bbox_xyxy/);
  assert.match(page, /context\.setLineDash/);
  assert.match(page, /!hasPolygon && track\.bbox_xyxy/);
  assert.match(page, /for \(const track of currentFrame\?\.tracks \?\? \[\]\)/);
  assert.match(page, /track\.track_id === hoveredContour\?\.id/);
  assert.match(page, /\{hoveredContour\.id\} \{hoveredContour\.label\}/);
  assert.match(page, /catalog\.tracks\.filter\(\(track\) => track\.label === type\)/);
  assert.match(page, /trackIds\.every\(\(id\) => selectedTracks\.has\(id\)\)/);
  assert.doesNotMatch(page, /selectedTypes|setSelectedTypes/);
  assert.match(page, /interaction_type: type/);
  assert.match(page, /const type = interactionType\.trim\(\)/);
  assert.match(page, /value=\{interactionType\}/);
  assert.match(page, /object_id_list: \[\.\.\.selectedTracks\]\.sort\(naturalCompare\)/);
  assert.match(page, /start_time: annotationTime\(currentAnnotationTime\)/);
  assert.match(page, /end_time: null/);
  assert.match(page, /nextInteractionId\(interactions\)/);
  assert.match(page, /return `i\$\{index\}`/);
  assert.match(page, /nextManualObjectId\(manualObjects\)/);
  assert.match(page, /return `m\$\{index\}`/);
  assert.match(page, /function createManualObject/);
  assert.match(page, /function appendManualObjectPoint/);
  assert.match(page, /function deleteLastManualObjectPoint/);
  assert.match(page, /function saveManualObject/);
  assert.match(page, /function selectManualObject/);
  assert.match(page, /Click the video to append polygon points/);
  assert.match(page, /manual_objects: sortedManualObjects/);
  assert.match(page, /checked=\{selectedTracks\.has\(manualObject\.object_id\)\}/);
  assert.match(page, /onChange=\{\(\) => toggleTrack\(manualObject\.object_id\)\}/);
  assert.match(page, /manualObject\.object_id !== editingManualObjectId\s*&& selectedTracks\.has\(manualObject\.object_id\)/);
  assert.match(page, /if \(manualObjectDraft\) \{/);
  assert.match(page, /appendManualObjectPoint\(event\)/);
  assert.match(page, /manualObjectIds\.has\(objectId\)/);
  assert.match(page, /Load manual objects and interactions/);
  assert.match(page, /Existing interactions will be preserved/);
  assert.match(page, /existing interactions were preserved/);
  assert.match(page, /manualObjectJsonInputRef\.current\?\.click\(\)/);
  const manualObjectLoader = page.slice(
    page.indexOf("async function loadManualObjectsJson"),
    page.indexOf("function stepFrame"),
  );
  assert.match(manualObjectLoader, /setManualObjects\(loadedManualObjects\)/);
  assert.doesNotMatch(manualObjectLoader, /setInteractions\(/);
  assert.doesNotMatch(manualObjectLoader, /setInteractionDraft\(/);
  assert.match(page, /aria-label="Load manual objects JSON"/);
  assert.match(page, /aria-label="Export manual objects JSON"/);
  assert.match(page, /onClick=\{exportInteractions\}/);
  assert.match(page, /id="interaction-id"/);
  assert.match(page, /id="interaction-edit-type"/);
  assert.match(page, /interaction_type: event\.target\.value/);
  assert.match(page, /interaction_id: interactionDraft\.interaction_id\.trim\(\)/);
  assert.match(page, /Interaction ID \$\{savedInteraction\.interaction_id\} is already in use/);
  assert.match(page, /Use current time as end/);
  assert.match(page, /Use current time as start/);
  assert.match(page, /Jump to start/);
  assert.match(page, /saveInteraction/);
  assert.match(page, /discardInteraction/);
  assert.match(page, /function deleteInteraction/);
  assert.match(page, /current\.filter/);
  assert.match(page, /interaction\.interaction_id !== interactionId/);
  assert.match(page, /onClick=\{deleteInteraction\}/);
  assert.match(page, /Delete interaction/);
  assert.match(page, /Export JSON to save this change/);
  assert.match(page, /seek\(interaction\.start_time\)/);
  assert.match(page, /setSelectedTracks\(new Set\(interaction\.object_id_list\)\)/);
  assert.match(page, /\.sort\(naturalCompare\)/);
  assert.match(page, /setInteractionDraft\(\{ \.\.\.interactionDraft, object_id_list: objectIds \}\)/);
  assert.doesNotMatch(page, /randomUUID|interaction-\$\{/);
  assert.match(page, /list="interaction-type-options"/);
  assert.match(page, /<datalist id="interaction-type-options">/);
  assert.match(page, /video: data\?\.video \|\| videoPath/);
  assert.match(page, /contour: contourPath/);
  assert.match(page, /interaction_list: sortedInteractions/);
  assert.match(page, /new Blob/);
  assert.match(page, /\.interactions\.json/);
  assert.match(page, /Jump to end/);
  assert.match(page, /disabled=\{!hasInteractionChanges\}/);
  assert.match(page, /setInteractionDraft\(cloneInteraction\(interaction\)\)/);
  assert.match(page, /interaction\.interaction_id === editingInteractionId \? savedInteraction : interaction/);
  assert.match(page, /window\.alert/);
  assert.match(page, /window\.confirm/);
  assert.match(page, /frame\.frame_index >= firstFrameIndex/);
  assert.match(page, /track\.contours_xy\.some\(\(contour\) => contour\.length >= 3\)/);
  assert.doesNotMatch(page, /onClick=\{createInteraction\} disabled=/);
  assert.match(page, /Saved interactions or manual objects have not been exported/);
  assert.match(page, /setData\(null\)/);
  assert.match(page, /setInteractions\(\[\]\)/);
  assert.match(page, /setJsonName\("No control file selected"\)/);
  assert.match(page, /setExportedInteractionSignature\(interactionSignature\)/);
  assert.match(page, />Clear selection<\/button>/);
  assert.match(page, /seekToFrame\(targetIndex\)/);
  assert.match(page, /function seekToFrame/);
  assert.match(page, /function startFrameStepping/);
  assert.match(page, /function stopFrameStepping/);
  assert.match(page, /STEP_HOLD_DELAY_MS/);
  assert.match(page, /STEP_REPEAT_MS/);
  assert.match(page, /onPointerCancel=\{stopFrameStepping\}/);
  assert.match(page, /onLostPointerCapture=\{stopFrameStepping\}/);
  assert.match(page, /followingFrame\.timestamp_seconds - targetFrame\.timestamp_seconds/);
  assert.match(page, /setCurrentTime\(targetFrame\.timestamp_seconds\)/);
  assert.doesNotMatch(page, /video\.currentTime \+ direction \/ fps/);
  assert.match(page, /cadence\.variable \? "VFR · "/);
  assert.match(page, /function parseVisualAids/);
  assert.match(page, /function drawReferenceLine/);
  assert.match(page, /headerObject\.visual_aids/);
  assert.match(page, /data\.visual_aids\.lines/);
  assert.match(page, /line\.points/);
  assert.match(page, /Lines on/);
  assert.match(page, /Lines off/);
  assert.match(page, /aria-pressed=\{showLineOverlay\}/);
});
